server:
  port: 8800

spring:
  application:
    name: sys-celebrity

  profiles:
    active: dev

  datasource:
    username: schoolHW
    password: hxajsWGfc6amwf52
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://1.15.86.236:3306/schoolhw?user=host&password=Mw7UUumKrcnSsqyx&useUnicode=true

  servlet :
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  redis:
    host: 43.143.241.157
    port: 6379
    password: 123456
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s

mybatis-plus:
  configuration:
    #日志
    #在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#  global-config:
#    db-config:
#      logic-delete-field: delFlag
#      logic-delete-value: 1
#      logic-not-delete-value: 0
#      id-type: auto
