server:
  port: 8800

spring:
  application:
    name: sys-celebrity

  datasource:
    username: schoolHW
    password: hxajsWGfc6amwf52
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://1.15.86.236:3306/schoolhw?user=host&password=Mw7UUumKrcnSsqyx&useUnicode=true

  servlet :
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB


mybatis-plus:
  configuration:
    #日志
    #在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#  # 搜索指定包别名
#  typeAliasesPackage: com.example.common
#  # 配置mapper的扫描，找到所有的mapper.xml映射文件
#  mapperLocations: classpath*:mapper/*.xml


#  global-config:
#    db-config:
#      logic-delete-field: delFlag
#      logic-delete-value: 1
#      logic-not-delete-value: 0
#      id-type: auto
